---
title: "KML (GPS), XML & Auszeichnungssprachen"
author: 
 - Christoph Rinne^[Christian-Albrechts-Universität zu Kiel, crinne@ufg.uni-kiel.de]
date: "`r format(Sys.time(), '%d. %B %Y')`"
license: "CC-BY 4.0"
header-includes:
  \renewcommand{\contentsname}{Inhalt}
  \renewcommand{\figurename}{Abb.}
  \renewcommand{\tablename}{Tab.}
papersize: a4
output:
  pdf_document:
    number_sections: true
    toc: true
    toc_depth: 2
    df_print: kable
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
fig_caption: true
urlcolor: blue
link-citations: true # make citations hyperlinks
linkcolor: blue
lang: de-DE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Allgemeine Information

Der Titel ist etwas hochtrabend und es wird nicht eine Einführung in [XML](https://de.wikipedia.org/wiki/Extensible_Markup_Language) werden, sondern es geht darum, Ihnen die Organisation von [Auszeichnungssprachen](https://de.wikipedia.org/wiki/Auszeichnungssprache) etwas näher zu bringen. Ich nutze dazu [KML](https://de.wikipedia.org/wiki/Keyhole_Markup_Language)-Dateien, die Sie ggf. schon von [Google Earth](https://www.google.com/intl/de_ALL/earth/versions/#earth-pro) kennen. 

Auszeichnungssprachen sollen Text gliedern, strukturieren, formatieren oder auch dem Text in einem definierten Kontext Bedeutung geben. Dies erfolgt, indem Textabschnitt von sogenannte *tags* eingeschlossen werden. Auszeichnungssprachen sind vorrangig maschinenlesbar und sollen plattformunabhängig den Datenaustausch zwischen Computern ermöglichen. Daten in einer allgemeingültig definierten XML-Struktur sind also eine gute Grundlage für nachhaltige Interoperabilität. Ein Beispiel das sie sicher schon mal gehört und gesehen haben ist HTML (Hypertext Markup Language), die genuine Sprache des Internets. 

```
<!--Beispiel für HTML-->
<p>
    <h2>Die Macht der Computer und die Ohnmacht der Vernunft</h2>
    <i>by <b>J. Weizenbaum</b></i>
    Frankfurt am Main 1977
</p>

<!--Beispiel für inhaltliche Strukturierung (XML)-->
<book>        
    <title>Die Macht der Computer und die Ohnmacht der Vernunft</title>
    <author>J. Weizenbaum</author>
    <place>Frankfurt am Main</place>
    <year>1977</year>    
</book>

```
HTML zielt auf das Layout von Text, XML hingegen zielt allgemein auf die Definition einer Auszeichnungssprache, auf deren Grundlage eine Strukturierung von Daten in einzelnen **Elemente** erfolgt. Diese Elemente sollen dem beinhalteten Text eine Bedeutung zuweisen, z.B. als Autor kenntlich machen. Die Strukturdefinition einer XML basierten Datei wird in einem frei zugänglichem Dokument abgelegt, der  Document Type Description (DTD) und auf dieses am Anfang der Datei verwiesen oder aber innerhalb des XML-basierten Dokumentes abgelegt.

Ziel dieser Übung wird es nicht, XML-Dateien von Hand zu schreiben, sondern eben grundlegende Strukturen zu erkennen und ggf. manipulieren oder nachnutzen zu können. Als Beispiel verwende ich KML.

# KML

Es handelt sich um eine Auszeichnungssprache für Geodaten. Aktuell finden Sie überwiegend KMZ-Dateien, es sind komprimierte (zip) Projektordner mit KML-Dateien.  KML ist als Standard vom Open Geospatial Consortium (OGC) akzeptiert und umfassend dokumentiert ([OGC Dokument](http://docs.opengeospatial.org/is/12-007r2/12-007r2.html)). Das zuvor referenzierte Dokument thematisiert mit didaktischen Bildern zugleich Fragen der Projektion. Etwas lesefreundlicher ist die Dokumentation der Erweiterungen bei [Google](https://developers.google.com/kml/documentation/kmlreference?csw=1). Insgesamt ist KML für die Archäologie durchaus sehr interessant, denn es bietet Raum für ergänzende Sachinformationen. Hier unterscheidet es sich von Well-Known-Text [WKT](https://de.wikipedia.org/wiki/Simple_Feature_Access#Well-known_Text), hier werden ausschließlich Geometrien beschrieben. 

## Punktgeometrien

Öffnen Sie die Datei "BBG_Siedlungen" mit Notepad++ und wählen Sie bei den Sprachen XML. Dadurch erhalten sie eine farbliche Differenzierung der Syntax und am linken Rand mit den Linien, [-] und [+] die Möglichkeit, die geschachtelten Elemente auf- und zuzuklappen. Sie erkennen die Zusammenhänge zudem durch die Einrückungen und den *start tag* ```<kml>``` und den *end tag* ```</kml>```. Natürlich gibt es weitere Bedingungen und Ausnahmen, so z.B. *tags* ohne *end tag*.

```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">
<Document>
    <name>BBG Siedlungen, Höhen- und Talrandlage</name>
    <open>1</open>
    <Style id="sn_bbg_sdl">
    <Style id="sh_bbg_sdl">
    <StyleMap id="ms_bbg_sdl">
    <Placemark>
    ...
</Document>
</kml>
```

Das erste *tag* verweist auf die xml-Version und die verwendete Kodierung. Und wenn Sie bis zum Ende der Datei springen finden Sie kein *end tag*.     
Das zweite *tag* \<kml> hat ein *end tag*, führt aber innerhalb des *start tags* eine lange Liste von Verweisen auf die verwendeten DTD (s.o.), die essentielle steht am Anfang, die anderen erweitern die Syntax. Diese Verweise dienen der automatisierten Verarbeitung zur Validierung der Syntax.     

Das dritte Element ist ein Dokument innerhalb des kml-Elementes, es entspricht einem Ordner mit Geometrieobjekten bei Google Earth. Entsprechend sehen sie als erstes Element innerhalb dieses Ordners einen *name tag* gefolgt von der Eigenschaft ob aufgeklappt oder geschlossen. Der weitere Abschnitt innerhalb des *document tag* wirkt erst etwas unübersichtlich, deshalb ist die obige Darstellung "zusammengeklappt". 

Für die Darstellung der Geometrien werden als erstes Darstellungsstile definiert, innerhalb des  *start tag* stet stets eine ID, diese Bezeichnung ist frei wählbar, minimalistische Lesbarkeit schadet aber nicht. "sn_bbg_sdl": Symbol für normal dargestellte Bernburger Siedlung, "sh_bbg_sdl": Symbol für *highlighted* Bernburger Siedlung und "ms_bbg_sdl": *mapsymbol* für Bernburger Siedlung. Das letztere wird für die entsprechende Geometrie zu Kartierung gewählt und verweist auf die beiden vorgenannten je nachdem, ob das Element nun markiert wird oder eben nicht. Die Syntax innerhalb dieser Stile ist im vorliegen Fall recht simpel.

```
    <Style id="sn_bbg_sdl">
        <IconStyle>
            <color>ff0000aa</color>
            <scale>0.6</scale>
            <Icon>
                <href>http://maps.google.com/mapfiles/kml/shapes/homegardenbusiness.png</href>
            </Icon>
            <hotSpot x="0.5" y="0" xunits="fraction" yunits="fraction"/>
        </IconStyle>
        <LabelStyle>
            <scale>0</scale>
        </LabelStyle>
    </Style>
``` 

Der Stil hat einen Abschnitt für das Icon und einen für die Beschriftung. Die Eigenschaften *tags* sind weitgehend selbst erklärend und mal abgesehen von der im Internet üblichen Farbkodierung durchaus verständlich. Das *tag* <hotSpot/> darf erklärt weden. Durch den Schrägstrich am ende wird übrigens klar, es gibt kein *end tag*. Dieses *tag* beschreibt die Lage des Symbols zur angegebene Koordinate. Sollten Sie den Link auf das Icon angeklickt haben erkennen Sie, dass das Haus in der Karte mittig auf dem Punkt dargestellt wird. Die zum Stil gehörende Beschriftung wird mit der Größe 0, also nicht dargestellt.

Die Definition für den hervorgehobenen Stil wiederzugeben lohnt sich nicht wirklich, das Symbol wird lediglich größer dargestellt ```<scale>1</scale>``` und die Beschriftung wird mit der selben Anweisung in normaler Größe angezeigt. 

```
    <StyleMap id="ms_bbg_sdl">
        <Pair>
            <key>normal</key>
            <styleUrl>#sn_bbg_sdl</styleUrl>
        </Pair>
        <Pair>
            <key>highlight</key>
            <styleUrl>#sh_bbg_sdl</styleUrl>
        </Pair>
    </StyleMap>
```

Auch dies kann nicht viel weiter erklärt werden. Zentral ist das Element *key* das genau zwei Werte haben kann *normal* oder *higlight*. Daraus ergeben sich zwei Darstellungspaare mit dem jeweiligen Verweis auf einen zuvor definierten Stil.

Innerhalb des *Document tag* folgt nun eine lange Liste von Fundplätzen, die mit dem Element *Placemark* beschrieben werden.

```
    <Placemark>
        <name>Burgörner Weinberg</name>
        <LookAt>
            <longitude>11.50428795600097</longitude>
            <latitude>51.64067006920091</latitude>
            <altitude>0</altitude>
            <heading>0.0002321020520841536</heading>
            <tilt>0</tilt>
            <range>171.1583632529837</range>
            <altitudeMode>relativeToGround</altitudeMode>
        </LookAt>
        <styleUrl>#ms_bbg_sdl</styleUrl>
        <ExtendedData>
            <Data name="Literatur">
                <value>Müller 1990</value>
            </Data>
            <Data name="Fundart">
                <value>Siedlung</value>
            </Data>
        </ExtendedData>
        <Point>
            <coordinates>11.50428795600097,51.64067006920091,0</coordinates>
        </Point>
    </Placemark>
```

Die zugehörigen Elemente haben alle sprechende Namen. Das Element *LookAt* ist optional (kann also entfallen) und beschreibt detailliert die Ansicht auf die Geometrie. Im vorliegenden Fall ist es eine Reminiszenz der Datenzusammenstellung in Google Earth. Interessant ist das Element *ExtendedData*. Es erlaubt das Anhängen von Sachdaten in einer Liste aus Feldname und Feldwert. Die spätere Darstellung erfolgt als zweispaltige Tabelle mit dem Variablennamen in der ersten und dem zugehörigen Wert in der zweiten Spalte. 

Damit ist die Syntax für eine KML-Datei mit Fundpunkten und zugehörigen Sachdaten grundlegend beschrieben. Das ist nicht wirklich kompliziert und kann aus jeder Datenbank generiert werden. 

Wo ist der Unterschied zu einer CSV-Tabelle (UTF-8) mit Koordinaten als WKT? In vielen wichtigen Punkten gibt es keinen. Beides ist maschinenlesbar und dennoch auch für Menschen lesbar. Es werden Geometrien mit anhängenden Sachdaten verbunden. Beide Formate liegen als Text vor und sind damit einfach zu archivieren. Soweit kein Unterschied für die zentralen Informationen. KML ist per Definition in UTF-8 kodiert bei einer CSV-Datei ist das nicht der Fall, hier bestimmt das Betriebssystem die Kodierung (Windows: ANSI). CSV speichert die Daten als Tabelle in der uns geläufigen Form: eine Spalte je Attribut die bei fehlender Information einfach leer bleibt. KML ist hier viel effizienter und kompakter, es gibt definierte Attribute und nur die belegten werden am Objekt gelistet. Ein durchaus übliches Verfahren in der Datenorganisation, es setzt aber einheitliche Definition und Schreibweise der Attribute voraus. KML bietet mit der Darstellung und weiteren Definitionen natürlich mehr Optionen. Damit ist es aber abhängig von der Umgebung, z.B. liegt das Icon bei unserer Datei im Web, was sich natürlich ändern ließe. Die KML zielt also ergänzend auf eine visuelle als auch interaktive Darstellung und geht damit über die CSV deutlich hinaus. 

## Liniengeometrien

Nutzen Sie nachfolgend bitte die Datei: Hochbruecke.kml. Für die einfache Visualisierung sind in der Struktur der Syntax keine Unterschiede vorhanden, bei den Elementen zur Beschreibung und Interaktion aber schon. Das Ganze ist mit der vorangehenden Erläuterung zu den Punkten aber verständlich und kleine Variationen mit 0 und 1 für die Elemente \<extrude> und \<tesselate> erschließen sich bei der Betrachtung in Google Earth unmittelbar. Das Element \<altitudeMode> benötigt andere Werte: *relativeToGround*, *absolute* oder *clampToGround* und bedingt ebenfalls die Darstellung der Linie. 

```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">
<Document>
    <name>Hochbruecke</name>
    <Style id="route-hl">
        <LineStyle>
            <color>ff0000aa</color>
            <width>8</width>
        </LineStyle>
        <PolyStyle>
            <color></color>
        </PolyStyle>
    </Style>
    <Style id="route-n">
        <LineStyle>
            <color>ff0000aa</color>
            <width>2</width>
        </LineStyle>
        <PolyStyle>
            <color>ff7df5ff</color>
        </PolyStyle>
    </Style>
    <StyleMap id="route">
        <Pair>
            <key>normal</key>
            <styleUrl>#route-n</styleUrl>
        </Pair>
        <Pair>
            <key>highlight</key>
            <styleUrl>#route-hl</styleUrl>
        </Pair>
    </StyleMap>
    <Placemark>
        <name>Holtenau</name>
        <styleUrl>#route</styleUrl>
        <LineString>
            <extrude>1</extrude>
            <tessellate>1</tessellate>
            <altitudeMode>absolute</altitudeMode>
            <coordinates>
                10.12093796366777,54.36590694049225,39.99999999999999
                10.12109123715073,54.36643494457174,39.99999999999999
                10.12127580261095,54.36689379308591,39.99999999999999
                10.12146501336677,54.36735153011876,39.99999999999999
                10.12172279167329,54.36776565000539,39.99999999999999
                10.12187831244731,54.36838201838961,39.99999999999999
                10.12217427037541,54.36892432558026,39.99999999999999
                10.12231905470356,54.36943118392424,39.99999999999999
                10.12260799672135,54.36996726586428,39.99999999999999
                10.12286854180568,54.37067130582465,39.99999999999999
                10.12304780654306,54.37097445808439,39.99999999999999
                10.12335429706786,54.37135390598432,39.99999999999999 
            </coordinates>
        </LineString>
    </Placemark>
</Document>
</kml>
```

# GPS

## Allgemeine Information

GPS ist aus unserer heutigen Gesellschaft nicht mehr wegzudenken. Grund ist sicher das grundsätzliche Bedürfnis, den eigenen geographischen Standort zu bestimmen. Während für einige Jahre GPS-Handgeräte (u.a. von Garmin) weit verbreitet waren, ist für viele Nutzer das Smartphone der Alleskönner und stets dabei. Daneben gibt es professionellere Geräte mit speziellen Antennen und ergänzende Dienste zur Fehlerkorrektur mit einer hohen Genauigkeit bei wenigen Zentimetern im Ergebnis (differentielles GPS).

Im folgenden soll nicht auf die hochpräzise Vermessung und die notwendigen Voraussetzungen eingegangen werden. Vielmehr soll es um Alltagsanwendungen gehen und einige der möglichen Formate für den Austausch (NMEA) und die Archivierung (gpx, kml) von Rauminformationen als Punkt (**W**ay**P**oint) oder Polygon (track). 

## Formate für GPS-Daten

### NMEA
Dieses Format ist ein altes und sehr grundlegendes Format für die Kommunikation zwischen elektronischen Geräten. Die Definition betrifft auch die Schnittstellenparameter, so z.B. die Baudrate, die die Anzahl der übermittelten Symbole pro Sekunde angibt. Viel wesentlicher oder umfangreicher sind die Definitionen diverser Informationseinheiten, deren Syntax und die Kombination in definierten Datensätzen. Natürlich gibt es über die Entwicklung mehrere Versionen, weit verbreitet ist NMEA 0183. NMEA ist textbasiert, hervorragend dokumentiert, maschinenlesbar, auch menschenlesbar und kompakt. NMEA wird von allen GPS-Geräte geliefert und ist der Standard für GPS Daten. Eine Einschränkung betrifft den Umfang der Informationen. Nicht jede Information muss in dem Datensatz vorhanden sein und nicht alle Datensätze sind zu liefern. Das System ist also Modular und so besteht keine Pflicht, Daten zur Anzahl der verwendeten Satelliten oder Präzision zu liefern. Die Firma hinter [NMEA](https://www.nmea.org) bietet keine direkte kostenlose Dokumentation und verweist lediglich auf veraltete Datensätze (depricated). Insgesamt sind aber brauchbare Voraussetzungen für eine nachhaltige Archivierung und Nutzung gegeben. Sie finden weitere Informationen natürlich bei [Wikipedia](https://de.wikipedia.org/wiki/NMEA_0183) und zu den NMEA 0183 Datensätzen im Web, u.a. [hier](http://www.nmea.de/nmea0183datensaetze.html).

```
$GPGGA,074914.000,5420.5647,N,1007.0718,E,1,00,0.0,27.6,M,0.0,M,,*6B
$GPRMC,074914.000,A,5420.5647,N,1007.0718,E,2.4,000.0,220411,,,A*58
```

Vorangehend ein kurzer Ausschnitt aus dem Datenstrom (NMEA 0183) einer kleinen GPS-Maus, die via USB-Kabel an diverse Endgeräte gebunden werden kann, aktuelle Geräte setzen auf Bluetooth. Das Gerät liefert genau zwei Datensätze: 
- GGA: *Global Positioning System Fix Data, Time, Position and fix related data for a GPS receiver*
- RMC: *Recommended Minimum Navigation Information*

Die Informationen innerhalb des Datensatzes sind durch "," getrennt. 

```                                                      11
        1         2       3 4        5 6 7  8   9  10 |  12 13  14   15
        |         |       | |        | | |  |   |   | |   | |   |    |
 $--GGA,hhmmss.ss,llll.ll,a,yyyyy.yy,a,x,xx,x.x,x.x,M,x.x,M,x.x,xxxx*hh<CR><LF>
```
Die einzelnen Abschnitte liefern folgende Information : Beispiel aus dem Datenstrom 
  1) Universal Time Coordinated (UTC) : 07(hh)49(mm)14(ss).000
  2) Latitude : 5420.5647
  3) N or S (North or South) : N
  4) Longitude : 1007.0718
  5) E or W (East or West) : E
  6) GPS Quality Indicator, : 1
     0 - fix not available,
     1 - GPS fix,
     2 - Differential GPS fix
  7) Number of satellites in view, 00 - 12 : 00
  8) Horizontal Dilution of precision : 0.0
  9) Antenna Altitude above/below mean-sea-level (geoid) : 27.6 
 10) Units of antenna altitude, meters : M
 11) Geoidal separation, the difference between the WGS-84 earth
     ellipsoid and mean-sea-level (geoid), "-" means mean-sea-level
     below ellipsoid : 0.0
 12) Units of geoidal separation, meters : M
 13) Age of differential GPS data, time in seconds since last SC104
     type 1 or 9 update, null field when DGPS is not used : <leer>
 14) Differential reference station ID, 0000-1023 <leer>
 15) Checksum *6B

```
        1         2 3       4 5        6 7   8   9    10  11|
        |         | |       | |        | |   |   |    |   | |
 $--RMC,hhmmss.ss,A,llll.ll,a,yyyyy.yy,a,x.x,x.x,xxxx,x.x,a*hh<CR><LF>
```

Die einzelnen Abschnitte liefern folgende, teils zu GGA redundante Information. Neu sind hier Geschwindigkeit und Datum. 
  1) UTC Time
  2) Status, V = Navigation receiver warning, P = Precise : A(utonom)
  3) Latitude
  4) N or S
  5) Longitude
  6) E or W
  7) Speed over ground, knots : 2.4 kn (=4,5 km/h)
  8) Track made good, degrees true
  9) Date, ddmmyy : 22(dd)04(mm)11(yy)
 10) Magnetic Variation, degrees
 11) E or W
 12) Checksum
  
### GPX (GPS)
Dieses Format ist das **GP**S-e**X**change format. Es basiert auf XML, es ist standardisiert und umfassend dokumentiert [Website](https://www.topografix.com/gpx.asp). Auch ist mehr möglich, als üblicherweise in vielen GPX-Dateien drinsteht, so z.B. die Anzahl der Satelliten, die Präzision (hdop, vdop, pdop) oder ein fix (Korrektursignal). Die Syntax und Struktur in dieser einfache Form ist in den wesentlichen Elementen selbsterklärend.

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<gpx version="1.0" creator="GPSBabel - http://www.gpsbabel.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.topografix.com/GPX/1/0" xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd">
<time>2011-04-22T14:45:24Z</time>
<bounds minlat="54.342745" minlon="10.044113" maxlat="54.484567" maxlon="10.167649" />
<trk>
<name>Track 11-04-22 09:46~11-04-22 13:12</name>
<trkseg>
<trkpt lat="54.342745" lon="10.117863">
<ele>27.6</ele>
<time>2011-04-22T07:49:14Z</time>
<speed>1.3</speed>
</trkpt>
[... optionale weitere Punkte ...]
</trkseg>
</trk>
```  

## Software und Anwendung

### GPS Babel

Quelle: https://www.gpsbabel.org
Ergänzende Infos: https://de.wikipedia.org/wiki/GPSBabel
Plattformunabhängige freie Software (GPL) für das Konvertieren von GPS-Dateien. Die Software bietet unter Windows und MacOS neben der Kommandozeile auch eine GUI. Interessant sind auch die zahlreichen Konvertierungen innerhalb von GPX zwischen *waypoint*, *track *und *rout*.

### QGIS GPS-Werkzeug (Erweiterug) & GPS-Information (Bedienfeld)

Qunatum GIS ([QGIS](https://qgis.org/)) ist ein sehr weit verbreitetes freies Geographisches Informations System. GPS-Werkzeuge sind ein integraler und nur zu aktivierender Bestandteile, der Zugriff erfolgt über das zu ergänzende Bedienfeld GPS-Informationen. Damit wird eine Verbindung zu einem externen GPS-Gerät aufgebaut. Unter Windows erfolgt diese Verbindung über einen COM-Port via USB-Kabel oder Bluetooth. Die mit der gewählten Frequenz, z.B. 1 Hz, einlaufenden Daten können direkt zur Digitalisierung genutzt werden.

### GeoSetter

Quelle: https://geosetter.de
Download: https://geosetter.de/download-de/
OS: ab Win 7
Diese Software verbindet Bilder mit Koordinaten aus GPS-Tracks (Mobiltelefon, Navi, GPS-Maus etc.) über Datum und Uhrzeit miteinander oder weist Koordinaten anhand einer Markierung in der benachbarten Karte zu. Das Verorten der Bilder von Exkursionen, Bodendenkmälern oder auch Ausgrabungen ist so einfach möglich (*geotaggen*). Zudem können automatisch Höhenangaben und Verwaltungsinformationen (Ort, Kreis, Land) von [GeoNames](http://www.geonames.org/) abgefragt und in den Metadaten der Bilder ergänzt werden.

Das Programm nutzt die Google Maps API für ihre notwendige Funktionalität, damit ist zugleich die Verwendung eines aktuellen Internetexplorers für die Karte unabdingbar ([s. Erläuterung der Website](https://geosetter.de/2018/05/10/geosetter-and-internet-explorer-de/)). Es kann aber auch eine OSM-Karte hinterlegt werden. Ein weitere essentieller, externer Bestandteile ist das Programms [ExifTool von Phil Harvey](https://www.sno.phy.queensu.ca/~phil/exiftool/) zum Lesen/Schreiben der Metadaten der Bilder. 

Ein Beispielhafter Arbeitsablauf:

- öffnen Sie links den Ordner der Bilder
- Um Tracks zu laden muss ggf. das entsprechende Fenster unter "Ansicht -> Tracks" geöffnet werden (\<strg>+\<t>). Laden Sie dann den zugehörigen *track*, er wird in der Karte dargestellt. 
- Markieren Sie die zu lokalisierenden Bilder und wählen dann "Bearbeiten -> Synchronisierund mit GPS-Daten" (\<strg>+\<g>)
- Im folgenden Fenster können zahlreiche Parameter angepasst werden, dies betrifft vor allem die Zeitangaben für die Synchronisation.
- In dem Kontextmenü der markierten Bilder "Daten bearbeiten" wählen (\<strg>+\<e>). Im folgenden Fenster können normierte Metadaten (IPTC, EXIF) bearbeitet werden. Im Register "Ort" können 1. die jeweilige Höhe nach SRTM oder TOPO und 2. die Verwaltungsangaben bei [GeoNames](http://www.geonames.org/) nachgeschlagen werden. 
- Die Änderungen müssen dezidiert gespeichert werden (Geduld!).

